### ISSUE TITLE
[BUG] [Subsystem] Arm extention and retraction 

### ISSUE THREAD

**Issue by Rkortlandt** [5152Alotobots/5152_ChargedUp#22]
**Describe the bug**
When extending the arm we are noticing some stuttering 

**Subsystem Details (please complete the following information):**
- Name: Arm Subsystem

**Expected behavior**
Smoth extention and retraction without going outside of min and max

**Comment by SeanErn** [comment]
Can you give me more information, please? Perhaps a suggestion to where you think the issue is coming from?

**Comment by SeanErn** [comment]
Implemented
