### ISSUE TITLE
[REQUEST] [Low] Flip over top  

### ISSUE THREAD

**Issue by Rkortlandt** [5152Alotobots/5152_ChargedUp#23]
**Describe the solution you'd like**
Use PID to flip over the top of the robot. To the back "Zone"

**Describe alternatives you've considered**
Useing trig to calculate the hight and width of the robot to not execed bounds 
Useing a look up table to see how far out you can be at any point.

**Comment by SeanErn** [comment]
Implemented by @chrisdeboer
